name: R-CI

on:
  push:
  pull_request:

jobs:
  R-CI:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - uses: actions/checkout@v3

      - name: Check package
        run: |
          sudo dnf --assumeyes install ansible
          git clone https://github.com/stewid/ansible-r-ci.git ../ansible-r-ci
          ansible-playbook -i localhost, ../ansible-r-ci/r-ci.yml
